package com.ouisani.aios.user.tools;

import com.ouisani.aios.core.config.AiosPaths;
import com.ouisani.aios.core.importance.ImportanceRecord;
import com.ouisani.aios.core.importance.ImportanceStore;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * 离线 Role Subset Optimizer — 借鉴 DyLAN 的 {@code proc_lists.py:41-45}。
 * <p>
 * DyLAN 在 dev set 上对每个 task type 跑多组角色子集，按 importance + accuracy 选最优子集，
 * 论文 MMLU 提升 25%。neuron-java 第一版<strong>不枚举子集</strong>（角色池小，枚举成本可控但 follow-up），
 * 改为<strong>按平均 importance 降序选 top-K</strong> — 同等价值但实现量级更轻。
 * <p>
 * <b>输入</b>：{@link ImportanceStore#loadAll()} 读 {@code ~/.aios/boulders/importance.jsonl}
 * （由 {@link com.ouisani.aios.user.apps.omnifactory.WorkflowEngine#printExecutionSummary}
 * 在每次工作流结束时累积写入）。
 * <p>
 * <b>算法</b>：
 * <ol>
 *   <li>按 {@code taskType} 分组所有 ImportanceRecord</li>
 *   <li>对每个 taskType，聚合 role → List&lt;importance&gt;（跨多次运行累积）</li>
 *   <li>算 role 的平均 importance，按降序排，取 top-K</li>
 * </ol>
 * <p>
 * <b>输出</b>：{@code bouldersDir()/role_subset_recommendation.yaml}：
 * <pre>
 *   # Auto-generated by RoleSubsetOptimizer
 *   crypto_price_tracker:
 *     - coder
 *     - reviewer
 *     - tester
 * </pre>
 * <p>
 * <b>不接入 TopologyCompiler</b>：本工具只产出推荐表，编译期选角色是 follow-up
 * （需 TopologyCompiler 改造 + 角色池冲突解决）。
 *
 * <h2>CLI</h2>
 * <pre>
 *   java -cp target/classes com.ouisani.aios.user.tools.RoleSubsetOptimizer [--topK 3]
 * </pre>
 * <ul>
 *   <li>{@code --topK N} — 每个 taskType 推荐的角色数（默认 3）</li>
 *   <li>{@code --minRuns N} — taskType 累积运行数 &lt; N 时跳过（统计不显著，默认 2）</li>
 *   <li>{@code --out PATH} — 输出路径覆盖（默认 bouldersDir/role_subset_recommendation.yaml）</li>
 * </ul>
 */
public final class RoleSubsetOptimizer {

    private static final Logger log = LoggerFactory.getLogger(RoleSubsetOptimizer.class);
    private static final String DEFAULT_OUTPUT_NAME = "role_subset_recommendation.yaml";
    private static final int DEFAULT_TOP_K = 3;
    private static final int DEFAULT_MIN_RUNS = 2;

    private RoleSubsetOptimizer() {}

    public static void main(String[] args) {
        int topK = DEFAULT_TOP_K;
        int minRuns = DEFAULT_MIN_RUNS;
        Path outOverride = null;

        for (int i = 0; i < args.length; i++) {
            String a = args[i];
            switch (a) {
                case "--topK" -> topK = parseIntArg(args, ++i, a, DEFAULT_TOP_K);
                case "--minRuns" -> minRuns = parseIntArg(args, ++i, a, DEFAULT_MIN_RUNS);
                case "--out" -> outOverride = (i + 1 < args.length) ? Path.of(args[++i]) : null;
                case "-h", "--help" -> {
                    printUsage();
                    return;
                }
                default -> System.err.println("[RoleSubsetOptimizer] 未知参数: " + a);
            }
        }

        if (topK < 1) {
            System.err.println("[RoleSubsetOptimizer] --topK 必须 >= 1，实际: " + topK);
            return;
        }

        Path inputFile = ImportanceStore.importanceFile();
        Path outputFile = outOverride != null ? outOverride
                : Path.of(AiosPaths.bouldersDir(), DEFAULT_OUTPUT_NAME);

        System.out.printf("[RoleSubsetOptimizer] 输入: %s%n", inputFile);
        System.out.printf("[RoleSubsetOptimizer] 输出: %s%n", outputFile);
        System.out.printf("[RoleSubsetOptimizer] 配置: topK=%d, minRuns=%d%n%n", topK, minRuns);

        List<ImportanceRecord> records = ImportanceStore.loadAll();
        if (records.isEmpty()) {
            System.err.println("[RoleSubsetOptimizer] 无 importance 记录。先跑若干工作流累积数据再优化。");
            System.err.println("  期望路径: " + inputFile);
            return;
        }

        System.out.printf("[RoleSubsetOptimizer] 加载 %d 条 importance 记录%n", records.size());

        Map<String, String> yaml = optimize(records, topK, minRuns);
        try {
            Files.createDirectories(outputFile.getParent());
            Files.writeString(outputFile, yaml.get("body"));
            System.out.printf("%n[RoleSubsetOptimizer] ✓ 推荐表已生成: %s%n", outputFile);
            System.out.println("[RoleSubsetOptimizer] 统计:");
            System.out.print(yaml.get("stats"));
        } catch (Exception e) {
            log.error("[RoleSubsetOptimizer] 写出失败: {}", e.getMessage());
            System.err.println("[RoleSubsetOptimizer] ✗ 写出失败: " + e.getMessage());
            System.exit(1);
        }
    }

    /**
     * 核心优化算法 — 公开静态方法，供单测直接调用（避免 main 的 System.exit 干扰测试）。
     *
     * @param records 全部 importance 记录
     * @param topK    每个 taskType 保留的角色数
     * @param minRuns taskType 累积运行数阈值，低于此值跳过（统计不显著）
     * @return Map 含两键：body=推荐表 YAML（String），stats=人类可读统计摘要
     */
    public static Map<String, String> optimize(List<ImportanceRecord> records, int topK, int minRuns) {
        // 1. 按 taskType 分组
        Map<String, List<ImportanceRecord>> byTaskType = new TreeMap<>();
        for (ImportanceRecord r : records) {
            String tt = r.taskType() != null && !r.taskType().isBlank() ? r.taskType() : "(unknown)";
            byTaskType.computeIfAbsent(tt, k -> new ArrayList<>()).add(r);
        }

        // 2. 每个 taskType 算 role 平均 importance，降序取 top-K
        Map<String, List<String>> recommendation = new TreeMap<>();
        StringBuilder stats = new StringBuilder();
        for (Map.Entry<String, List<ImportanceRecord>> e : byTaskType.entrySet()) {
            String taskType = e.getKey();
            List<ImportanceRecord> recs = e.getValue();
            if (recs.size() < minRuns) {
                stats.append(String.format("  %-40s SKIP (运行数 %d < %d 阈值)%n",
                        taskType, recs.size(), minRuns));
                continue;
            }

            // role → List<importance>（跨多次运行累积）
            Map<String, List<Double>> roleImp = new LinkedHashMap<>();
            for (ImportanceRecord r : recs) {
                for (Map.Entry<String, Double> ri : r.roleImportance().entrySet()) {
                    roleImp.computeIfAbsent(ri.getKey(), k -> new ArrayList<>()).add(ri.getValue());
                }
            }

            // 算平均，按降序排
            List<Map.Entry<String, Double>> avg = new ArrayList<>();
            for (Map.Entry<String, List<Double>> re : roleImp.entrySet()) {
                double sum = 0.0;
                for (Double v : re.getValue()) sum += v;
                avg.add(Map.entry(re.getKey(), sum / re.getValue().size()));
            }
            avg.sort(Comparator.<Map.Entry<String, Double>>comparingDouble(Map.Entry::getValue).reversed());

            // 取 top-K
            List<String> topRoles = new ArrayList<>();
            int limit = Math.min(topK, avg.size());
            for (int i = 0; i < limit; i++) {
                topRoles.add(avg.get(i).getKey());
            }
            if (!topRoles.isEmpty()) {
                recommendation.put(taskType, topRoles);
            }

            // 统计摘要
            stats.append(String.format("  %-40s 运行 %d 次 | roles: ", taskType, recs.size()));
            for (int i = 0; i < limit; i++) {
                Map.Entry<String, Double> ae = avg.get(i);
                stats.append(String.format("%s(%.3f) ", ae.getKey(), ae.getValue()));
            }
            stats.append("\n");
        }

        // 3. 序列化为 YAML
        String yaml = renderYaml(recommendation, byTaskType, topK, minRuns);
        Map<String, String> result = new LinkedHashMap<>();
        result.put("body", yaml);
        result.put("stats", stats.toString());
        return result;
    }

    /** 渲染推荐表为 YAML 字符串 — 手写，不引 Jackson/YAML 库到 user/tools。 */
    private static String renderYaml(Map<String, List<String>> recommendation,
                                     Map<String, List<ImportanceRecord>> byTaskType,
                                     int topK, int minRuns) {
        StringBuilder sb = new StringBuilder(256);
        String ts = DateTimeFormatter.ISO_INSTANT.format(Instant.now().atZone(ZoneOffset.UTC));
        sb.append("# Auto-generated by RoleSubsetOptimizer at ").append(ts).append(" (UTC)\n");
        sb.append("# Sorted by avg importance descending; top-K=").append(topK)
                .append(", minRuns=").append(minRuns).append("\n");
        sb.append("# Source: ~/.aios/boulders/importance.jsonl\n\n");

        if (recommendation.isEmpty()) {
            sb.append("# (空) — 无 taskType 达到 minRuns=").append(minRuns).append(" 阈值\n");
            return sb.toString();
        }

        for (Map.Entry<String, List<String>> e : recommendation.entrySet()) {
            sb.append(escapeYamlKey(e.getKey())).append(":\n");
            for (String role : e.getValue()) {
                sb.append("  - ").append(escapeYamlScalar(role)).append("\n");
            }
            sb.append("\n");
        }
        return sb.toString();
    }

    private static int parseIntArg(String[] args, int idx, String name, int dflt) {
        if (idx >= args.length) {
            System.err.println("[RoleSubsetOptimizer] " + name + " 缺少参数值");
            return dflt;
        }
        try {
            return Integer.parseInt(args[idx].trim());
        } catch (NumberFormatException ex) {
            System.err.println("[RoleSubsetOptimizer] " + name + " 不是合法整数: " + args[idx]);
            return dflt;
        }
    }

    /** YAML key 转义 — 简化处理，role/taskType 一般为 [a-z_]+，但保险起见含特殊字符加引号。 */
    private static String escapeYamlKey(String s) {
        return needsQuote(s) ? "\"" + s.replace("\"", "\\\"") + "\"" : s;
    }

    private static String escapeYamlScalar(String s) {
        return needsQuote(s) ? "\"" + s.replace("\"", "\\\"") + "\"" : s;
    }

    private static boolean needsQuote(String s) {
        if (s == null || s.isEmpty()) return true;
        // YAML plain scalar 需引号的情形（YAML 1.2 spec）：
        // 1. 以指示字符开头（- ? : , [ ] { } # & * ! | > ' " % @ `）
        //    注意：- 在 key 中间合法（task-X），只在开头才需引号
        char first = s.charAt(0);
        if ("-?:,[]{}#&*!|>'\"%@`".indexOf(first) >= 0) return true;
        // 2. 以空格开头/结尾
        if (Character.isWhitespace(first) || Character.isWhitespace(s.charAt(s.length() - 1))) return true;
        // 3. 包含 ": "（冒号+空格，被解析为 key-value 分隔）或以 ":" 结尾
        if (s.contains(": ") || s.endsWith(":")) return true;
        // 4. 包含 " #"（空格+井号，被解析为注释）或以 # 开头
        if (s.contains(" #") || s.startsWith("#")) return true;
        // 5. 包含换行/制表符
        if (s.indexOf('\n') >= 0 || s.indexOf('\r') >= 0 || s.indexOf('\t') >= 0) return true;
        // 6. 看起来像数字（避免被解析为 int/float）
        if (Character.isDigit(first) || first == '+') return true;
        // 7. YAML 1.1 boolean/null 字面量
        String lower = s.toLowerCase();
        if (lower.equals("true") || lower.equals("false") || lower.equals("yes") || lower.equals("no")
                || lower.equals("null") || lower.equals("~") || lower.equals("on") || lower.equals("off")) return true;
        return false;
    }

    private static void printUsage() {
        System.out.println("""
                RoleSubsetOptimizer — 离线角色子集优化器（借鉴 DyLAN proc_lists.py）

                用法:
                  java -cp target/classes com.ouisani.aios.user.tools.RoleSubsetOptimizer [--topK N] [--minRuns N] [--out PATH]

                参数:
                  --topK N      每个 taskType 推荐的角色数（默认 3）
                  --minRuns N   taskType 累积运行数阈值，低于此值跳过（默认 2）
                  --out PATH    输出路径覆盖（默认 ~/.aios/boulders/role_subset_recommendation.yaml）
                  -h, --help    打印此帮助

                示例:
                  java -cp target/classes com.ouisani.aios.user.tools.RoleSubsetOptimizer
                  java -cp target/classes com.ouisani.aios.user.tools.RoleSubsetOptimizer --topK 5 --minRuns 3
                """);
    }
}
