export NODE_ID=research_existing_solutions
export INPUT_TOPIC=
export OUTPUT_TOPIC=topic_research_existing_solutions_design_core_components
python3 /factory/research_existing_solutions.py &
export NODE_ID=design_core_components
export INPUT_TOPIC=topic_research_existing_solutions_design_core_components
export OUTPUT_TOPIC=topic_design_core_components_design_api_and_protocol,topic_design_core_components_implement_coordinator
python3 /factory/design_core_components.py &
export NODE_ID=design_api_and_protocol
export INPUT_TOPIC=topic_design_core_components_design_api_and_protocol
export OUTPUT_TOPIC=topic_design_api_and_protocol_implement_producer_client,topic_design_api_and_protocol_implement_consumer_worker
python3 /factory/design_api_and_protocol.py &
export NODE_ID=create_project_structure
export INPUT_TOPIC=
export OUTPUT_TOPIC=topic_create_project_structure_implement_task_model
python3 /factory/create_project_structure.py &
export NODE_ID=implement_task_model
export INPUT_TOPIC=topic_create_project_structure_implement_task_model
export OUTPUT_TOPIC=topic_implement_task_model_implement_queue_backend,topic_implement_task_model_implement_result_store
python3 /factory/implement_task_model.py &
export NODE_ID=implement_queue_backend
export INPUT_TOPIC=topic_implement_task_model_implement_queue_backend
export OUTPUT_TOPIC=topic_implement_queue_backend_implement_producer_client,topic_implement_queue_backend_implement_consumer_worker
python3 /factory/implement_queue_backend.py &
export NODE_ID=implement_producer_client
export INPUT_TOPIC=topic_implement_queue_backend_implement_producer_client,topic_design_api_and_protocol_implement_producer_client
export OUTPUT_TOPIC=topic_implement_producer_client_integration_test_suite
python3 /factory/implement_producer_client.py &
export NODE_ID=implement_consumer_worker
export INPUT_TOPIC=topic_implement_queue_backend_implement_consumer_worker,topic_design_api_and_protocol_implement_consumer_worker
export OUTPUT_TOPIC=topic_implement_consumer_worker_integration_test_suite
python3 /factory/implement_consumer_worker.py &
export NODE_ID=implement_result_store
export INPUT_TOPIC=topic_implement_task_model_implement_result_store
export OUTPUT_TOPIC=topic_implement_result_store_integration_test_suite
python3 /factory/implement_result_store.py &
export NODE_ID=implement_coordinator
export INPUT_TOPIC=topic_design_core_components_implement_coordinator
export OUTPUT_TOPIC=topic_implement_coordinator_integration_test_suite
python3 /factory/implement_coordinator.py &
export NODE_ID=integration_test_suite
export INPUT_TOPIC=topic_implement_producer_client_integration_test_suite,topic_implement_consumer_worker_integration_test_suite,topic_implement_result_store_integration_test_suite,topic_implement_coordinator_integration_test_suite
export OUTPUT_TOPIC=topic_integration_test_suite_generate_documentation
python3 /factory/integration_test_suite.py &
export NODE_ID=generate_documentation
export INPUT_TOPIC=topic_integration_test_suite_generate_documentation
export OUTPUT_TOPIC=
python3 /factory/generate_documentation.py &
